### ISSUE TITLE
Discussion: PGOperationGroup.parallel

### ISSUE THREAD

**Issue by sssinghsyr** [pgjdbc/pgsql2#15]
PGOperationGroup.parallel states - "postgresql wire format doesn't allow parallel queries".

Using single connection, parallelism cannot be achieved. But can we assign multiple connections to a single OperationGroup and handle multiple Operations in parallel?
I want to understand the USE_CASE of OperationGroup!

**Comment by alexanderkjall** [comment]
I think that letting one OperationGroup handle multiple connections would break the principle of least surprise, specially as starting a connection is a pretty expensive operation and every connection started results in a process fork on the database side.

Regarding OperationGroup: This is something I have struggled a lot with also, the OperationGroup class introduces a lot of complexity without having a super clear benefit for the user. With that said there is some use case for the 'held' functionality, it kind of works as a union query, but for more kinds of queries, read the class PGOperationGroupTest for examples.

I guess that there also is a flow control use case, with canceling of queries and catchOperation() but I haven't implemented that correctly yet, and to be honest I don't really see why it's needed.

It is also useful to be able to group a number of queries, and specify a timeout for all of them together, the timeout logic is still in need of implementation.

**Comment by davecramer** [comment]
Technically it is possible to issue multiple requests and get multiple
answers back. That said it's difficult to decompose the multiple messages
as there are no tags on the messages.


Dave Cramer
