### ISSUE TITLE
java.sql2.DataSourceFactoryManager seems to be work in progress

### ISSUE THREAD

**Issue by alexanderkjall** [pgjdbc/pgsql2#3]
I have tried to get service discovery working, but it looks as the service discovery code in DataSourceFactoryManager isn't in use and the code isn't complete yet.

I think we need to do the Class.forName thing to load the DataSourceFactory.

**Comment by davecramer** [comment]
My first thought and why I stopped was I figured we would have to write all of that stuff as it doesn't exist yet for java 10

**Comment by alexanderkjall** [comment]
Seems like this is fixed now, with the DataSourceFactory.forName("org.postgresql.sql2.PGDataSourceFactory") construct.
