### ISSUE TITLE
Use testcontainers to setup a reproducible test envirorment 

### ISSUE THREAD

**Issue by alexanderkjall** [pgjdbc/pgsql2#9]
This project: https://www.testcontainers.org/

It will be possible to build test suites that runs the tests against different versions of postgresql and also develop the driver without requiring any other local setup than docker.

**Comment by davecramer** [comment]
How does this differ from Travis?

**Comment by cretz** [comment]
Alternatively, or at least to get started quickly or have it easily work on everyone's checkout, see https://github.com/yandex-qatools/postgresql-embedded/. I have successfully used this to test multiple versions of Postgres.

**Comment by alexanderkjall** [comment]
I think it fills two different use cases, travis is great for verifying that all commits and pull requests that get pushed to the github passes the tests.

Testcontainers is good for running the tests locally while developing.

I will investigate postgresql-embedded also.

**Comment by cretz** [comment]
Also, feel free to take code from https://github.com/cretz/pgnio/blob/ce6a3a7e5b08047cf29436bda17f3e1f8da5f41d/driver/src/test/java/pgnio/EmbeddedDb.java. I had to jump through a couple of hoops wrt SSL keys.

**Comment by davecramer** [comment]
Awesome sounds interesting
